import * as functions from "./modules/functions.js";

functions.burger()
functions.sliderEmployees()
functions.sliderReviews()
functions.sliderCertificates()
functions.sliderServices()
functions.wordSlice()
functions.showMore()
functions.modalEmployee()
functions.modalForm()
functions.masks()
functions.validateCallback()
functions.validateModalForm()
functions.aosAnim()
functions.lazyIframe()
functions.lazyMap()
functions.playViedeo()